name: Build and deploy PHP app to Azure Web App - NutriBox

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - uses: actions/checkout@v4

      # Step to set up PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      # Step to check if composer.json exists
      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      # Step to install composer dependencies
      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      # Step to zip the deployment files
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      # Step to upload the artifact for deployment
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Step to download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      # Step to unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step to deploy to Azure Web App using publish-profile
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'NutriBox'  # Ensure this matches your actual App Service name
          slot-name: 'Production'  # If using slots, otherwise remove this line
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
